amazonProperties:
  endpointUrl: https://121239911243.signin.aws.amazon.com/console
  accessKey: AKIARYOTWHNFYGMPGDVL
  secretKey: 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
  bucketName: haiderproject3